# Generated by Django 3.2.16 on 2023-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('first_curr', models.CharField(max_length=3)),
                ('second_curr', models.CharField(max_length=3)),
                ('third_curr', models.CharField(max_length=3)),
            ],
        ),
    ]
