# Generated by Django 3.2.16 on 2023-02-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencypreference',
            name='id',
        ),
        migrations.AlterField(
            model_name='currencypreference',
            name='first_curr',
            field=models.CharField(default='BTC', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencypreference',
            name='second_curr',
            field=models.CharField(default='ETH', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencypreference',
            name='third_curr',
            field=models.CharField(default='SOL', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencypreference',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
