# Generated by Django 3.2.16 on 2023-04-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tradepair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradePair',
        ),
    ]
